### ISSUE TITLE
Hit Ratio over 100% and zero Bandwidth?

### ISSUE THREAD

**Issue by dancriel** [ITLinuxCL/Varnish-Agent-Dashboard#3]
I just compiled varnish-agent from source on CentOS and installed Varnish-Agent-Dashboard to replace the default HTML.

My Hit Ratio graph is showing almost 500% (sometimes over), and my Bandwidth graph is showing zero.  The Requests / second graph seems to work ok.  All 3 graphs have data below the graph populated in the table.

Any ideas?

![screen shot 2014-12-10 at wednesday 12-10-14 - 4 58 pm](https://cloud.githubusercontent.com/assets/10147396/5385132/cd6a4476-808d-11e4-8965-96b7219e4316.png)

**Comment by brandonwamboldt** [comment]
@dancriel This dashboard isn't maintained, but I've been working on a replacement with more functionality. Check it out:

https://github.com/brandonwamboldt/varnish-dashboard
