### ISSUE TITLE
How to load on startup automatically?

### ISSUE THREAD

**Issue by JordanMagnuson** [ITLinuxCL/Varnish-Agent-Dashboard#4]
I've got varnish-agent and this dashboard up and running.

I have varnish-agent installed from the debian package, and it starts automatically on system start.

My question is: how/where do I modify varnish-agent config in order to get varnish-agent-dashboard to load as the html frontend automatically on system start? 

(So that I don't have to manually enter `varnish-agent -H /var/www/html/Varnish-Agent-Dashboard` every time).

**Comment by JordanMagnuson** [comment]
Information on the package is available at https://github.com/varnish/vagent2/blob/master/INSTALL.rst

**Comment by pbruna** [comment]
@JordanMagnuson on Debian you have the `/etc/default/varnish-agent` file where the you can define the options the program must start with.

So you should have something like:

```
DAEMON_OPTS="-H /var/www/html/Varnish-Agent-Dashboard"
```

**Comment by JordanMagnuson** [comment]
Thanks, works like a charm :)
